name: Finalize Classes

on: [pull_request, push]

jobs:
    finalize_classes:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.1', '7.2']

        name: "PHP ${{ matrix.php_version }}"

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: |
                    mkdir temp && cd temp
                    composer require doctrine/orm --ansi --no-interaction
                    ../bin/rector process ../ci/downgrade/tests/fixture-finalize --config ../ci/downgrade/rector-finalize.php --ansi

