name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1

            # Upload the artifact so we can download and review the downgraded code
            -   run: mkdir build
            -   uses: montudor/action-zip@v0.1.1
                with:
                    args: zip -X -r build/rector-php71.zip . -x *.git* .* "*/\.*" build** ci** stubs** tests** "**/tests**"
            -   uses: actions/upload-artifact@v2
                with:
                    name: rector-downgraded-code
                    path: build/rector-php71.zip

            # Run all the tests on PHP 7.4 (because JUnit needs PHP 7.3+),
            # but using Rector downgraded to PHP 7.1
            -   run: vendor/bin/phpunit

            # Avoid Composer v2 platform checks (composer.json requires PHP 7.3+, but below we are running 7.1)
            -   run: composer config platform-check false
            # Regenerating the autoload files will remove vendor/composer/platform_check.php, otherwise executing bin/rector on 7.1 fails
            -   run: composer dumpautoload

            # Remove DEV dependencies
            -   run: composer install --ignore-platform-req=php --no-dev

            # Replace the composer.json file
            -   run: cp ci/downgrade/composer.json ./composer.json

            # Switch to PHP 7.1 and run PHPStan to analyze the code,
            # as to make sure no 7.2+ code was left behind (if there is, PHP will throw some error)
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            # The Symfony Polyfill libraries are needed
            -   run: composer require symfony/polyfill-php72 symfony/polyfill-php73 --ignore-platform-req=php

            # Rector without DEV needs phpstan.neon removed
            -   run: rm phpstan.neon

            # Override the artifact with downgraded Composer too
            -   run: rm build/rector-php71.zip
            -   uses: montudor/action-zip@v0.1.1
                with:
                    args: zip -X -r build/rector-php71.zip . -x *.git* .* "*/\.*" build**
            -   uses: actions/upload-artifact@v2
                with:
                    name: rector-downgraded-code
                    path: build/rector-php71.zip

            # Test the downgraded Rector by running the default set on its own src
            -   run: bin/rector process src --dry-run

            # Run PHPStan to make sure no PHP 7.2+ code was left behind
            -   run: vendor/bin/phpstan analyse -c ci/downgrade/phpstan.neon --ansi
