name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1

            # Upload the artifact so we can download and review the downgraded code
            -   run: mkdir build
            -   uses: montudor/action-zip@v0.1.0
                with:
                    args: zip -X -r build/rector-php71.zip . -x *.git* .* "*/\.*" build** tests**
            -   uses: actions/upload-artifact@v2
                with:
                    name: rector-php71
                    path: build/rector-php71.zip

            # Avoid Composer v2 platform checks (composer.json requires PHP 7.2, but we run 7.1 below)
            -   run: composer config platform-check false
            # Regenerating the autoload files will remove vendor/composer/platform_check.php, otherwise executing bin/rector on 7.1 fails
            -   run: composer dumpautoload

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.1
                    coverage: none

            # -   run: composer install --ignore-platform-req=php
            # -   run: composer phpstan
            # For testing, run downgraded Rector over its own src, for ALL sets!
            -   run: bin/rector process src --dry-run
