name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1

            # Upload the artifact so we can download and review the downgraded code
            -   run: mkdir build
            -   uses: montudor/action-zip@v0.1.1
                with:
                    args: zip -X -r build/rector-php71.zip . -x *.git* .* "*/\.*" build** ci** stubs** tests** "**/tests**"
            -   uses: actions/upload-artifact@v2
                with:
                    name: rector-downgraded-code
                    path: build/rector-php71.zip

            # Avoid Composer v2 platform checks (composer.json requires PHP 7.2, but we run 7.1 below)
            -   run: composer config platform-check false
            # Regenerating the autoload files will remove vendor/composer/platform_check.php, otherwise executing bin/rector on 7.1 fails
            -   run: composer dumpautoload

            # Run all the tests on PHP 7.4 (because JUnit needs PHP 7.3+),
            # but using Rector downgraded to PHP 7.1
            -   run: vendor/bin/phpunit

            # Switch to PHP 7.1 and run PHPStan to analyze the code,
            # as to make sure no 7.2+ code was left behind (if there is, PHP will throw some error)
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            # Change Composer's PHP requirement to 7.1
            # -   run: composer require php --ignore-platform-req=php

            # Test the downgraded Rector by running the default set on its own src
            -   run: bin/rector process src --dry-run

            # -   run: composer install --ignore-platform-req=php
            # -   run: vendor/bin/phpstan analyse --ansi --error-format symplify --level 0
